//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mol.Integration.Lib.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOL_Entities : DbContext
    {
        public MOL_Entities()
            : base("name=MOL_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOL_Consumer> MOL_Consumer { get; set; }
        public virtual DbSet<MOL_IntegrationService> MOL_IntegrationService { get; set; }
        public virtual DbSet<MOL_IntegrationServiceConsumer> MOL_IntegrationServiceConsumer { get; set; }
        public virtual DbSet<MOL_IntegrationServiceLogging> MOL_IntegrationServiceLogging { get; set; }
    }
}
