//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mol.Integration.Lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOL_IntegrationServiceConsumer
    {
        public int Id { get; set; }
        public short IntegrationServiceId { get; set; }
        public short ConsumerId { get; set; }
        public bool Revoke { get; set; }
    
        public virtual MOL_Consumer MOL_Consumer { get; set; }
        public virtual MOL_IntegrationService MOL_IntegrationService { get; set; }
    }
}
