//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mol.Integration.Services.Client.NICServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mol.gov.sa/services/", ConfigurationName="NICServiceReference.INICService")]
    public interface INICService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mol.gov.sa/services/INICService/CancelVisa", ReplyAction="http://mol.gov.sa/services/INICService/CancelVisaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Lib.Contract.Fault.NICFaultContract), Action="http://mol.gov.sa/services/INICService/CancelVisaNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        bool CancelVisa(double requestNumber, double borderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mol.gov.sa/services/INICService/QueryDependentsByID", ReplyAction="http://mol.gov.sa/services/INICService/QueryDependentsByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Lib.Contract.Fault.NICFaultContract), Action="http://mol.gov.sa/services/INICService/QueryDependentsByIDNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        Mol.Integration.Lib.Contract.Data.DependentsData QueryDependentsByID(double IdNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mol.gov.sa/services/INICService/GetLabrorPrisonStatus", ReplyAction="http://mol.gov.sa/services/INICService/GetLabrorPrisonStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Lib.Contract.Fault.NICFaultContract), Action="http://mol.gov.sa/services/INICService/GetLabrorPrisonStatusNICFaultContractFault" +
            "", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        bool GetLabrorPrisonStatus(double IdNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mol.gov.sa/services/INICService/AuthenticateUserByMobile", ReplyAction="http://mol.gov.sa/services/INICService/AuthenticateUserByMobileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Lib.Contract.Fault.NICFaultContract), Action="http://mol.gov.sa/services/INICService/AuthenticateUserByMobileNICFaultContractFa" +
            "ult", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        bool AuthenticateUserByMobile(double IdNo, string smsCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mol.gov.sa/services/INICService/Test", ReplyAction="http://mol.gov.sa/services/INICService/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Lib.Contract.Fault.NICFaultContract), Action="http://mol.gov.sa/services/INICService/TestNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        string Test(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INICServiceChannel : Mol.Integration.Services.Client.NICServiceReference.INICService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NICServiceClient : System.ServiceModel.ClientBase<Mol.Integration.Services.Client.NICServiceReference.INICService>, Mol.Integration.Services.Client.NICServiceReference.INICService {
        
        public NICServiceClient() {
        }
        
        public NICServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NICServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NICServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NICServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CancelVisa(double requestNumber, double borderNumber) {
            return base.Channel.CancelVisa(requestNumber, borderNumber);
        }
        
        public Mol.Integration.Lib.Contract.Data.DependentsData QueryDependentsByID(double IdNo) {
            return base.Channel.QueryDependentsByID(IdNo);
        }
        
        public bool GetLabrorPrisonStatus(double IdNo) {
            return base.Channel.GetLabrorPrisonStatus(IdNo);
        }
        
        public bool AuthenticateUserByMobile(double IdNo, string smsCode) {
            return base.Channel.AuthenticateUserByMobile(IdNo, smsCode);
        }
        
        public string Test(string Name) {
            return base.Channel.Test(Name);
        }
    }
}
