//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mol.Integration.Services.Client.NICServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
    [System.SerializableAttribute()]
    public partial class NICFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] InsertField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Insert {
            get {
                return this.InsertField;
            }
            set {
                if ((object.ReferenceEquals(this.InsertField, value) != true)) {
                    this.InsertField = value;
                    this.RaisePropertyChanged("Insert");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DependentsData", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class DependentsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.LookupStructure MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.NameStructure NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.LookupStructure NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.LookupStructure OccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.LookupStructure RelationshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.LookupStructure ReligionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.ResidencyStructure ResidencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.SponsorStructure SponsorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.StatusStructure StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.TravelStructure TravelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.VisaStructure VisaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.LookupStructure MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.NameStructure Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.LookupStructure Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.LookupStructure Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.LookupStructure Relationship {
            get {
                return this.RelationshipField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationshipField, value) != true)) {
                    this.RelationshipField = value;
                    this.RaisePropertyChanged("Relationship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.LookupStructure Religion {
            get {
                return this.ReligionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReligionField, value) != true)) {
                    this.ReligionField = value;
                    this.RaisePropertyChanged("Religion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.ResidencyStructure Residency {
            get {
                return this.ResidencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidencyField, value) != true)) {
                    this.ResidencyField = value;
                    this.RaisePropertyChanged("Residency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.SponsorStructure Sponsor {
            get {
                return this.SponsorField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorField, value) != true)) {
                    this.SponsorField = value;
                    this.RaisePropertyChanged("Sponsor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.StatusStructure Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.TravelStructure Travel {
            get {
                return this.TravelField;
            }
            set {
                if ((object.ReferenceEquals(this.TravelField, value) != true)) {
                    this.TravelField = value;
                    this.RaisePropertyChanged("Travel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.VisaStructure Visa {
            get {
                return this.VisaField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaField, value) != true)) {
                    this.VisaField = value;
                    this.RaisePropertyChanged("Visa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class DateStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GregorianDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GregorianDateSpecifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HijriDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GregorianDate {
            get {
                return this.GregorianDateField;
            }
            set {
                if ((this.GregorianDateField.Equals(value) != true)) {
                    this.GregorianDateField = value;
                    this.RaisePropertyChanged("GregorianDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GregorianDateSpecified {
            get {
                return this.GregorianDateSpecifiedField;
            }
            set {
                if ((this.GregorianDateSpecifiedField.Equals(value) != true)) {
                    this.GregorianDateSpecifiedField = value;
                    this.RaisePropertyChanged("GregorianDateSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HijriDate {
            get {
                return this.HijriDateField;
            }
            set {
                if ((object.ReferenceEquals(this.HijriDateField, value) != true)) {
                    this.HijriDateField = value;
                    this.RaisePropertyChanged("HijriDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class LookupStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class NameStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThirdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.NameStructure TranslatedNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThirdName {
            get {
                return this.ThirdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ThirdNameField, value) != true)) {
                    this.ThirdNameField = value;
                    this.RaisePropertyChanged("ThirdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.NameStructure TranslatedName {
            get {
                return this.TranslatedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslatedNameField, value) != true)) {
                    this.TranslatedNameField = value;
                    this.RaisePropertyChanged("TranslatedName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResidencyStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class ResidencyStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IdNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuePlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IdNo {
            get {
                return this.IdNoField;
            }
            set {
                if ((this.IdNoField.Equals(value) != true)) {
                    this.IdNoField = value;
                    this.RaisePropertyChanged("IdNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdType {
            get {
                return this.IdTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTypeField, value) != true)) {
                    this.IdTypeField = value;
                    this.RaisePropertyChanged("IdType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueDateField, value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuePlace {
            get {
                return this.IssuePlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuePlaceField, value) != true)) {
                    this.IssuePlaceField = value;
                    this.RaisePropertyChanged("IssuePlace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SponsorStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class SponsorStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IdNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.LookupStructure TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IdNo {
            get {
                return this.IdNoField;
            }
            set {
                if ((this.IdNoField.Equals(value) != true)) {
                    this.IdNoField = value;
                    this.RaisePropertyChanged("IdNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.LookupStructure Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class StatusStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FingerPrintStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.LookupStructure PersonStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrisonerStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FingerPrintStatus {
            get {
                return this.FingerPrintStatusField;
            }
            set {
                if ((this.FingerPrintStatusField.Equals(value) != true)) {
                    this.FingerPrintStatusField = value;
                    this.RaisePropertyChanged("FingerPrintStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.LookupStructure PersonStatus {
            get {
                return this.PersonStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonStatusField, value) != true)) {
                    this.PersonStatusField = value;
                    this.RaisePropertyChanged("PersonStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrisonerStatus {
            get {
                return this.PrisonerStatusField;
            }
            set {
                if ((this.PrisonerStatusField.Equals(value) != true)) {
                    this.PrisonerStatusField = value;
                    this.RaisePropertyChanged("PrisonerStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class TravelStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure EntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure LastEntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure LastExitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure PassportExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TravelStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure EntryDate {
            get {
                return this.EntryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryDateField, value) != true)) {
                    this.EntryDateField = value;
                    this.RaisePropertyChanged("EntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure LastEntryDate {
            get {
                return this.LastEntryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LastEntryDateField, value) != true)) {
                    this.LastEntryDateField = value;
                    this.RaisePropertyChanged("LastEntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure LastExitDate {
            get {
                return this.LastExitDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LastExitDateField, value) != true)) {
                    this.LastExitDateField = value;
                    this.RaisePropertyChanged("LastExitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure PassportExpiryDate {
            get {
                return this.PassportExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportExpiryDateField, value) != true)) {
                    this.PassportExpiryDateField = value;
                    this.RaisePropertyChanged("PassportExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TravelStatus {
            get {
                return this.TravelStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TravelStatusField, value) != true)) {
                    this.TravelStatusField = value;
                    this.RaisePropertyChanged("TravelStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisaStructure", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class VisaStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FinalExitVisaIssuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mol.Integration.Services.Client.NICServiceReference.DateStructure VisaExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisaTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FinalExitVisaIssued {
            get {
                return this.FinalExitVisaIssuedField;
            }
            set {
                if ((this.FinalExitVisaIssuedField.Equals(value) != true)) {
                    this.FinalExitVisaIssuedField = value;
                    this.RaisePropertyChanged("FinalExitVisaIssued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mol.Integration.Services.Client.NICServiceReference.DateStructure VisaExpiryDate {
            get {
                return this.VisaExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaExpiryDateField, value) != true)) {
                    this.VisaExpiryDateField = value;
                    this.RaisePropertyChanged("VisaExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaType {
            get {
                return this.VisaTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaTypeField, value) != true)) {
                    this.VisaTypeField = value;
                    this.RaisePropertyChanged("VisaType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NICServiceReference.INICService")]
    public interface INICService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INICService/CancelVisa", ReplyAction="http://tempuri.org/INICService/CancelVisaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Services.Client.NICServiceReference.NICFaultContract), Action="http://tempuri.org/INICService/CancelVisaNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        bool CancelVisa(double requestNumber, double borderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INICService/QueryDependentsByID", ReplyAction="http://tempuri.org/INICService/QueryDependentsByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Services.Client.NICServiceReference.NICFaultContract), Action="http://tempuri.org/INICService/QueryDependentsByIDNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        Mol.Integration.Services.Client.NICServiceReference.DependentsData QueryDependentsByID(double IdNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INICService/GetLabrorPrisonStatus", ReplyAction="http://tempuri.org/INICService/GetLabrorPrisonStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Services.Client.NICServiceReference.NICFaultContract), Action="http://tempuri.org/INICService/GetLabrorPrisonStatusNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        bool GetLabrorPrisonStatus(double IdNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INICService/AuthenticateUserByMobile", ReplyAction="http://tempuri.org/INICService/AuthenticateUserByMobileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Services.Client.NICServiceReference.NICFaultContract), Action="http://tempuri.org/INICService/AuthenticateUserByMobileNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        bool AuthenticateUserByMobile(double IdNo, string smsCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INICService/Test", ReplyAction="http://tempuri.org/INICService/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.Services.Client.NICServiceReference.NICFaultContract), Action="http://tempuri.org/INICService/TestNICFaultContractFault", Name="NICFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Mol.Integration.Lib.Contract.Fault")]
        string Test(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INICServiceChannel : Mol.Integration.Services.Client.NICServiceReference.INICService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NICServiceClient : System.ServiceModel.ClientBase<Mol.Integration.Services.Client.NICServiceReference.INICService>, Mol.Integration.Services.Client.NICServiceReference.INICService {
        
        public NICServiceClient() {
        }
        
        public NICServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NICServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NICServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NICServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CancelVisa(double requestNumber, double borderNumber) {
            return base.Channel.CancelVisa(requestNumber, borderNumber);
        }
        
        public Mol.Integration.Services.Client.NICServiceReference.DependentsData QueryDependentsByID(double IdNo) {
            return base.Channel.QueryDependentsByID(IdNo);
        }
        
        public bool GetLabrorPrisonStatus(double IdNo) {
            return base.Channel.GetLabrorPrisonStatus(IdNo);
        }
        
        public bool AuthenticateUserByMobile(double IdNo, string smsCode) {
            return base.Channel.AuthenticateUserByMobile(IdNo, smsCode);
        }
        
        public string Test(string Name) {
            return base.Channel.Test(Name);
        }
    }
}
